### ISSUE TITLE
Search results not acting as expected

### ISSUE THREAD

**Issue by sdbarron** [gahntpo/CatAPISwiftUI#2]
When searching for Y (for example - because the Abyssinian happens to be first), iOS inserts it as a capital so Abyssinian isn't included.

By adding lowercased() to both the name and the searchText...
`return breeds.filter {$0.name.lowercased().contains(searchText.lowercased())}`
...the search acts more like you might expect.

Sorry, I didn't do a pull request because this file isn't in the Repo yet.  😸 
I'm also more than willing to believe that there's a better way!
<img width="418" alt="Before" src="https://user-images.githubusercontent.com/661712/130369624-e9a54866-3a52-4b0d-bb18-650f8cb2fa34.png">
<img width="418" alt="After" src="https://user-images.githubusercontent.com/661712/130369623-4a1a54c9-c458-4591-b93e-62dae30da826.png">

**Comment by sdbarron** [comment]
P.S.  I know this isn't the point of the example - but this is a great start to a reference app!

**Comment by gahntpo** [comment]
Hey Steve,
thanks for notifying me. I had some problems in Xcode to create a GitHub repo. This used to be easy. Not sure if it is caused by me or Xcode beta.
Anyway, I added the missing file and checked if it is running okay.Fun fact: before I recorded the video, I was thinking "I must add the case insensitive search". But obviously forgot ;)
Have a nice MondayKarin  
    Am Montag, 23. August 2021, 02:18:28 OESZ hat Steve Barron ***@***.***> Folgendes geschrieben:  
 
 


P.S. I know this isn't the point of the example - but this is a great start to a reference app!


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
